# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LiveDontDie' do

 
pod 'Mapbox-iOS-SDK', '~> 3.6'
  # Pods for LiveDontDie
    pod 'Firebase', '~>3.17'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'SVProgressHUD'
    pod 'ChameleonFramework'

end
